[build]
builder = "RAILPACK"
buildCommand = "apt-get update && apt-get install -y python3 python3-pip python3-dev build-essential && npm install && chmod -R +x node_modules/.bin && npm rebuild bcrypt --build-from-source && python3 -m pip install uvicorn fastapi scikit-learn numpy joblib pydantic qiskit qiskit-machine-learning scipy --break-system-packages"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/api/health"
timeout = 300
